### ISSUE TITLE
Feature: Create an Issue Across all Repositories

### ISSUE THREAD

**Issue by SeanKilleen** [excellalabs/konmaripo#89]
We have a use case for this for an action we'll be undertaking. Figured I'd build it into this tool.

## Criteria

* [x] Enter the text of the message (#90)
* [x] See a preview of the text with the "Universal issue" appended (#90)
* [x] ~~Add the option to pin the issue~~ Not needed at this time.
* [x] Show the repo counts where the issue will be posted (#90)
* [x] Show the API request limit (#90)
* [x] ~~Predict how many requests will be used~~ (holding off on this)
* [x] Don't allow posting if API requests exceed remaining. (follow-up #95)
* [x] Add Danger zone style formatting to submitting the issue (#93)

Nice to haves:

* [x] Preview the message (GitHub Markdown parsing)
* [x] ~~Ability to cancel~~ Not worrying about this for now.
* [x] Add time of reset for API requests. (#94)
